### PR TITLE
Split grafana dashboards into recent & historical.  Adding InfluxDB s…

### PR DESCRIPTION
**Pull request by mikewalch**
…etup script to create

continuous queries and retention policies.

### CODE REVIEW

**Comment by keith-turner** [comment]
should docs/grafana.md be updated?

**Comment by mikewalch** [comment]
Yes, I updated grafana.md in 447abd965c88

**Comment by keith-turner** [comment]
I think it would be worth mentioning in the markdown docs the current 30 sec reporting requirement. I think this grafana/influxdb contrib expects clients to report on a 30 sec interval.

**Comment by mikewalch** [comment]
Mentioned the 30 sec requirement in bbc5aef2621d

**Comment by keith-turner** [comment]
+1

**Pull request merged**
